-- Import questions from NEW CAPS
-- Delete old questions first to avoid duplicates
DELETE FROM questions WHERE topic_id IN (13, 14, 15, 16, 17);

-- Insert new questions for Topic 13 (Introduction to OOP Concepts)
INSERT INTO `questions` (`id`, `topic_id`, `question_text`, `code_snippet`, `option_a`, `option_b`, `option_c`, `correct_option`, `class_level`, `question_type`) VALUES
(281, 13, 'What does OOP stand for?', '', 'Object Oriented Programming', 'Organized Object Programming', 'Optional Object Processing', 'A', 'Beginner', 'Quiz question'),
(282, 13, 'Which of the following is a fundamental principle of OOP?', '', 'Inheritance', 'Compilation', 'Debugging', 'A', 'Beginner', 'Quiz question'),
(283, 13, 'What is a class in OOP?', '', 'A running program', 'A blueprint for creating objects', 'A database table', 'B', 'Beginner', 'Quiz question'),
(284, 13, 'What is an object in OOP?', '', 'A variable', 'An instance of a class', 'A method', 'B', 'Beginner', 'Quiz question'),
(285, 13, 'In Java, what keyword is used to create a new object?', '', 'create', 'new', 'object', 'B', 'Beginner', 'Quiz question'),
(286, 13, 'What is the main benefit of using OOP?', '', 'Faster execution', 'Code reusability and organization', 'Less memory usage', 'B', 'Beginner', 'Quiz question'),
(287, 13, 'Which of these is NOT a pillar of OOP?', '', 'Encapsulation', 'Inheritance', 'Compilation', 'C', 'Beginner', 'Quiz question'),
(288, 13, 'What is encapsulation in OOP?', '', 'Creating multiple objects', 'Hiding internal details of a class', 'Inheriting from another class', 'B', 'Beginner', 'Quiz question'),
(289, 13, 'What is inheritance in OOP?', '', 'Creating new objects', 'A class acquiring properties from another class', 'Hiding data', 'B', 'Beginner', 'Quiz question'),
(290, 13, 'What is polymorphism in OOP?', '', 'Having multiple constructors', 'Same interface, different implementations', 'Creating private methods', 'B', 'Beginner', 'Quiz question'),
(291, 13, 'Which access modifier makes a member accessible only within the same class?', '', 'public', 'protected', 'private', 'C', 'Beginner', 'Quiz question'),
(292, 13, 'What is a constructor in OOP?', '', 'A method that destroys objects', 'A special method called when creating objects', 'A variable in a class', 'B', 'Beginner', 'Quiz question'),
(293, 13, 'What is the difference between a class and an object?', '', 'They are the same thing', 'Class is a blueprint, object is an instance', 'Class stores data, object stores methods', 'B', 'Beginner', 'Quiz question'),
(294, 13, 'Which keyword is used for inheritance in Java?', '', 'inherits', 'extends', 'implements', 'B', 'Beginner', 'Quiz question'),
(295, 13, 'What happens when you call a method on an object?', '', 'The object is destroyed', 'The method executes using the object''s data', 'A new object is created', 'B', 'Beginner', 'Quiz question'),
(296, 13, 'Given this class definition, what will happen when you create an object? String name; int age; } Student s = new Student();', 'class Student {', 'Compilation error', 'Object created with default values', 'Runtime error', 'B', 'Beginner', 'Simulation question'),
(297, 13, 'What is the output of this code? String brand = "Toyota"; } Car myCar = new Car();', 'class Car {\nSystem.out.println(myCar.brand);', 'null', 'Toyota', 'Compilation error', 'B', 'Beginner', 'Simulation question'),
(298, 13, 'Which line correctly creates an object of class Book? String title; String author; }', 'class Book {', 'Book.title = "Java Guide";', 'Book myBook = new Book();', 'Book();', 'B', 'Beginner', 'Simulation question'),
(299, 13, 'What will this code print? String name; } Person p = new Person(); p.name = "John";', 'class Person {\nSystem.out.println(p.name);', 'null', 'John', 'Compilation error', 'B', 'Beginner', 'Simulation question'),
(300, 13, 'Given this class, what is the correct way to access the field ''price''? } Product item = new Product();', 'class Product {\npublic double price;', 'item->price', 'item.price', 'item::price', 'B', 'Beginner', 'Simulation question'),
(301, 13, 'What happens when you run this code? void makeSound() { } }', 'class Animal {\nSystem.out.println("Some sound");\nAnimal a = new Animal();', 'Prints "Some sound"', 'Compilation error', 'Runtime error', 'A', 'Beginner', 'Simulation question'),
(302, 13, 'Which constructor call is correct for this class? int width, height; Rectangle(int w, int h) { width = w; height = h; } }', 'class Rectangle {', 'Rectangle r = new Rectangle();', 'Rectangle r = new Rectangle(5, 10);', 'Rectangle r = Rectangle(5, 10);', 'B', 'Beginner', 'Simulation question'),
(303, 13, 'What will be the value of ''count'' after this code executes? int count = 0; void increment() { count++; } } Counter c = new Counter();', 'class Counter {', '0', '1', '2', 'C', 'Beginner', 'Simulation question'),
(304, 13, 'What is the output of this inheritance example? void display() { } } } Child c = new Child();', 'class Parent {\nSystem.out.println("Parent");\nclass Child extends Parent {', 'Parent', 'Child', 'Compilation error', 'A', 'Beginner', 'Simulation question'),
(305, 13, 'Which method call is correct for this class? return a + b; } } Calculator calc = new Calculator();', 'class Calculator {\npublic int add(int a, int b) {', 'calc.add(5, 3)', 'Calculator.add(5, 3)', 'add(5, 3)', 'A', 'Beginner', 'Simulation question'),
(306, 13, 'What will this polymorphism example print? void sound() { System.out.println("Animal sound"); } } void sound() { System.out.println("Bark"); } }', 'class Animal {\nclass Dog extends Animal {\nAnimal a = new Dog();', 'Animal sound', 'Bark', 'Compilation error', 'B', 'Beginner', 'Simulation question'),
(307, 13, 'What is the result of accessing a private field from outside the class? } Example e = new Example();', 'class Example {\nprivate int value = 10;\nSystem.out.println(e.value);', 'Prints 10', 'Prints 0', 'Compilation error', 'C', 'Beginner', 'Simulation question'),
(308, 13, 'What happens with this encapsulation example? return balance; } } Account acc = new Account();', 'class Account {\nprivate double balance = 1000;\npublic double getBalance() {\nSystem.out.println(acc.getBalance());', 'Compilation error', 'Prints 1000.0', 'Prints 0.0', 'B', 'Beginner', 'Simulation question'),
(309, 13, 'Which object creation is valid for this class? String model; model = m; } }', 'class Phone {\nPhone(String m) {', 'Phone p = new Phone();', 'Phone p = new Phone("iPhone");', 'Phone p = Phone("iPhone");', 'B', 'Beginner', 'Simulation question'),
(310, 13, 'What will this method overriding example output? void start() { System.out.println("Vehicle starts"); } } void start() { System.out.println("Car starts"); } } Car c = new Car();', 'class Vehicle {\nclass Car extends Vehicle {', 'Vehicle starts', 'Car starts', 'Both messages', 'B', 'Beginner', 'Simulation question'),
(311, 13, 'What is method overloading in Java?', '', 'Overriding a method in subclass', 'Having multiple methods with same name but different parameters', 'Making a method private', 'B', 'Intermediate', 'Quiz question'),
(312, 13, 'Which of these demonstrates proper encapsulation?', '', 'Public fields with private methods', 'Private fields with public getter/setter methods', 'All fields and methods public', 'B', 'Intermediate', 'Quiz question'),
(313, 13, 'What is the super keyword used for in Java?', '', 'To create a new object', 'To call parent class constructor or methods', 'To make a method static', 'B', 'Intermediate', 'Quiz question'),
(314, 13, 'What is the difference between abstract class and interface?', '', 'No difference', 'Abstract class can have implementation, interface cannot (pre-Java 8)', 'Interface can have constructor, abstract class cannot', 'B', 'Intermediate', 'Quiz question'),
(315, 13, 'What is method overriding in inheritance?', '', 'Creating multiple methods with same name', 'Redefining a parent class method in child class', 'Making a method final', 'B', 'Intermediate', 'Quiz question'),
(316, 13, 'Which access modifier allows access within package and subclasses?', '', 'private', 'protected', 'default', 'B', 'Intermediate', 'Quiz question'),
(317, 13, 'What is composition in OOP?', '', 'Inheriting from multiple classes', 'Having objects as members of another class', 'Making all methods abstract', 'B', 'Intermediate', 'Quiz question'),
(318, 13, 'What does the final keyword do when applied to a class?', '', 'Makes all methods abstract', 'Prevents the class from being inherited', 'Makes the class static', 'B', 'Intermediate', 'Quiz question');
